// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchLead360Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchLead360() {
    driver.get("https://demo.cc360.dxnet.io/search360/search360");
    driver.manage().window().setSize(new Dimension(1280, 760));
    driver.findElement(By.cssSelector("#mat-select-0 > .mat-select-trigger")).click();
    driver.findElement(By.cssSelector("#mat-option-6 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-select-1 > .mat-select-trigger")).click();
    driver.findElement(By.cssSelector("#mat-option-36 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-select-2 > .mat-select-trigger")).click();
    driver.findElement(By.cssSelector("#mat-option-37 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-select-3 > .mat-select-trigger")).click();
    driver.findElement(By.cssSelector("#mat-option-39 > .mat-option-text")).click();
    driver.findElement(By.cssSelector("#mat-select-4 .mat-select-arrow")).click();
    driver.findElement(By.cssSelector("#mat-option-14 > .mat-option-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".mat-datepicker-toggle-default-icon")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(3) > .mat-calendar-body-cell:nth-child(2) > .mat-calendar-body-cell-content")).click();
    driver.findElement(By.cssSelector(".ng-star-inserted:nth-child(5) > .mat-calendar-body-cell:nth-child(7) > .mat-calendar-body-cell-content")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".save-button:nth-child(2) > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".cdk-focused > .mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
  }
}
